# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gimbal.ui'
#
# Created: Tue Dec  2 14:10:04 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormMain(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)
        
    def setupUi(self, FormMain):
        FormMain.setObjectName(_fromUtf8("FormMain"))
        FormMain.resize(616, 601)
        self.label = QtGui.QLabel(FormMain)
        self.label.setGeometry(QtCore.QRect(10, 200, 56, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(FormMain)
        self.label_2.setGeometry(QtCore.QRect(110, 200, 56, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.labelX = QtGui.QLabel(FormMain)
        self.labelX.setGeometry(QtCore.QRect(70, 200, 41, 16))
        self.labelX.setObjectName(_fromUtf8("labelX"))
        self.labelY = QtGui.QLabel(FormMain)
        self.labelY.setGeometry(QtCore.QRect(170, 200, 41, 16))
        self.labelY.setObjectName(_fromUtf8("labelY"))
        self.groupBox = QtGui.QGroupBox(FormMain)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 261, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 225, 91))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelPIDControllerRoll = QtGui.QLabel(self.gridLayoutWidget)
        self.labelPIDControllerRoll.setObjectName(_fromUtf8("labelPIDControllerRoll"))
        self.gridLayout.addWidget(self.labelPIDControllerRoll, 2, 0, 1, 1)
        self.spinPitchD = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinPitchD.setObjectName(_fromUtf8("spinPitchD"))
        self.gridLayout.addWidget(self.spinPitchD, 1, 3, 1, 1)
        self.labelP = QtGui.QLabel(self.gridLayoutWidget)
        self.labelP.setAlignment(QtCore.Qt.AlignCenter)
        self.labelP.setObjectName(_fromUtf8("labelP"))
        self.gridLayout.addWidget(self.labelP, 0, 1, 1, 1)
        self.spinRollD = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinRollD.setObjectName(_fromUtf8("spinRollD"))
        self.gridLayout.addWidget(self.spinRollD, 2, 3, 1, 1)
        self.spinRollP = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinRollP.setObjectName(_fromUtf8("spinRollP"))
        self.gridLayout.addWidget(self.spinRollP, 2, 1, 1, 1)
        self.labelI = QtGui.QLabel(self.gridLayoutWidget)
        self.labelI.setAlignment(QtCore.Qt.AlignCenter)
        self.labelI.setObjectName(_fromUtf8("labelI"))
        self.gridLayout.addWidget(self.labelI, 0, 2, 1, 1)
        self.labelPIDControllerPitch = QtGui.QLabel(self.gridLayoutWidget)
        self.labelPIDControllerPitch.setObjectName(_fromUtf8("labelPIDControllerPitch"))
        self.gridLayout.addWidget(self.labelPIDControllerPitch, 1, 0, 1, 1)
        self.spinPitchP = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinPitchP.setObjectName(_fromUtf8("spinPitchP"))
        self.gridLayout.addWidget(self.spinPitchP, 1, 1, 1, 1)
        self.spinPitchI = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinPitchI.setObjectName(_fromUtf8("spinPitchI"))
        self.gridLayout.addWidget(self.spinPitchI, 1, 2, 1, 1)
        self.spinRollI = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinRollI.setObjectName(_fromUtf8("spinRollI"))
        self.gridLayout.addWidget(self.spinRollI, 2, 2, 1, 1)
        self.labelD = QtGui.QLabel(self.gridLayoutWidget)
        self.labelD.setAlignment(QtCore.Qt.AlignCenter)
        self.labelD.setObjectName(_fromUtf8("labelD"))
        self.gridLayout.addWidget(self.labelD, 0, 3, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(274, 120, 21, 20))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.groupBox_2 = QtGui.QGroupBox(FormMain)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 311, 51))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.buttonConnect = QtGui.QPushButton(self.groupBox_2)
        self.buttonConnect.setGeometry(QtCore.QRect(230, 18, 81, 30))
        self.buttonConnect.setObjectName(_fromUtf8("buttonConnect"))
        self.listConnect = QtGui.QComboBox(self.groupBox_2)
        self.listConnect.setGeometry(QtCore.QRect(10, 20, 221, 26))
        self.listConnect.setObjectName(_fromUtf8("listConnect"))
        self.groupBox_3 = QtGui.QGroupBox(FormMain)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 50, 331, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 306, 41))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelSensorAxisTop = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSensorAxisTop.setObjectName(_fromUtf8("labelSensorAxisTop"))
        self.gridLayout_2.addWidget(self.labelSensorAxisTop, 0, 0, 1, 1)
        self.labelSensorAxisRight = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSensorAxisRight.setObjectName(_fromUtf8("labelSensorAxisRight"))
        self.gridLayout_2.addWidget(self.labelSensorAxisRight, 0, 2, 1, 1)
        self.listAxisTop = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.listAxisTop.setObjectName(_fromUtf8("listAxisTop"))
        self.gridLayout_2.addWidget(self.listAxisTop, 0, 1, 1, 1)
        self.listAxisRight = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.listAxisRight.setObjectName(_fromUtf8("listAxisRight"))
        self.gridLayout_2.addWidget(self.listAxisRight, 0, 3, 1, 1)
        self.checkBoxSkipCalibration = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxSkipCalibration.setGeometry(QtCore.QRect(10, 90, 181, 18))
        self.checkBoxSkipCalibration.setObjectName(_fromUtf8("checkBoxSkipCalibration"))
        self.buttonCalibAccel = QtGui.QPushButton(self.groupBox_3)
        self.buttonCalibAccel.setGeometry(QtCore.QRect(0, 110, 121, 32))
        self.buttonCalibAccel.setObjectName(_fromUtf8("buttonCalibAccel"))
        self.buttonCalibGyro = QtGui.QPushButton(self.groupBox_3)
        self.buttonCalibGyro.setGeometry(QtCore.QRect(130, 110, 121, 32))
        self.buttonCalibGyro.setObjectName(_fromUtf8("buttonCalibGyro"))
        self.buttonRead = QtGui.QPushButton(FormMain)
        self.buttonRead.setGeometry(QtCore.QRect(370, 200, 121, 32))
        self.buttonRead.setObjectName(_fromUtf8("buttonRead"))
        self.buttonWrite = QtGui.QPushButton(FormMain)
        self.buttonWrite.setGeometry(QtCore.QRect(490, 200, 121, 32))
        self.buttonWrite.setObjectName(_fromUtf8("buttonWrite"))
        self.labelStatus = QtGui.QLabel(FormMain)
        self.labelStatus.setGeometry(QtCore.QRect(10, 580, 591, 16))
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.textStatus = QtGui.QTextEdit(FormMain)
        self.textStatus.setGeometry(QtCore.QRect(10, 230, 601, 331))
        self.textStatus.setObjectName(_fromUtf8("textStatus"))

        self.retranslateUi(FormMain)
        QtCore.QMetaObject.connectSlotsByName(FormMain)

    def retranslateUi(self, FormMain):
        FormMain.setWindowTitle(_translate("FormMain", "Main Window", None))
        self.label.setText(_translate("FormMain", "Accel X", None))
        self.label_2.setText(_translate("FormMain", "Accel Y", None))
        self.labelX.setText(_translate("FormMain", "--.----", None))
        self.labelY.setText(_translate("FormMain", "--.----", None))
        self.groupBox.setTitle(_translate("FormMain", "PID Controller:", None))
        self.labelPIDControllerRoll.setText(_translate("FormMain", "Roll", None))
        self.labelP.setText(_translate("FormMain", "P", None))
        self.labelI.setText(_translate("FormMain", "I", None))
        self.labelPIDControllerPitch.setText(_translate("FormMain", "Pitch", None))
        self.labelD.setText(_translate("FormMain", "D", None))
        self.checkBox.setText(_translate("FormMain", "CheckBox", None))
        self.groupBox_2.setTitle(_translate("FormMain", "Connect:", None))
        self.buttonConnect.setText(_translate("FormMain", "Connect", None))
        self.groupBox_3.setTitle(_translate("FormMain", "Sensor:", None))
        self.labelSensorAxisTop.setText(_translate("FormMain", "Axis Top", None))
        self.labelSensorAxisRight.setText(_translate("FormMain", "Right", None))
        self.checkBoxSkipCalibration.setText(_translate("FormMain", "Skip Calibration on Startup", None))
        self.buttonCalibAccel.setText(_translate("FormMain", "Calib Accel", None))
        self.buttonCalibGyro.setText(_translate("FormMain", "Calib Gyro", None))
        self.buttonRead.setText(_translate("FormMain", "READ", None))
        self.buttonWrite.setText(_translate("FormMain", "WRITE", None))
        self.labelStatus.setText(_translate("FormMain", "Status:", None))

