# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './console/console_view.ui'
#
# Created: Sat Apr  4 17:08:13 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ConsoleView(object):
    def setupUi(self, ConsoleView):
        ConsoleView.setObjectName(_fromUtf8("ConsoleView"))
        ConsoleView.resize(906, 595)
        self.label = QtGui.QLabel(ConsoleView)
        self.label.setGeometry(QtCore.QRect(10, 200, 56, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(ConsoleView)
        self.label_2.setGeometry(QtCore.QRect(110, 200, 56, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.labelX = QtGui.QLabel(ConsoleView)
        self.labelX.setGeometry(QtCore.QRect(70, 200, 41, 16))
        self.labelX.setObjectName(_fromUtf8("labelX"))
        self.labelY = QtGui.QLabel(ConsoleView)
        self.labelY.setGeometry(QtCore.QRect(170, 200, 41, 16))
        self.labelY.setObjectName(_fromUtf8("labelY"))
        self.groupBox = QtGui.QGroupBox(ConsoleView)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 261, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 225, 91))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelPIDControllerRoll = QtGui.QLabel(self.gridLayoutWidget)
        self.labelPIDControllerRoll.setObjectName(_fromUtf8("labelPIDControllerRoll"))
        self.gridLayout.addWidget(self.labelPIDControllerRoll, 2, 0, 1, 1)
        self.spinPitchD = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinPitchD.setObjectName(_fromUtf8("spinPitchD"))
        self.gridLayout.addWidget(self.spinPitchD, 1, 3, 1, 1)
        self.labelP = QtGui.QLabel(self.gridLayoutWidget)
        self.labelP.setAlignment(QtCore.Qt.AlignCenter)
        self.labelP.setObjectName(_fromUtf8("labelP"))
        self.gridLayout.addWidget(self.labelP, 0, 1, 1, 1)
        self.spinRollD = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinRollD.setObjectName(_fromUtf8("spinRollD"))
        self.gridLayout.addWidget(self.spinRollD, 2, 3, 1, 1)
        self.spinRollP = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinRollP.setObjectName(_fromUtf8("spinRollP"))
        self.gridLayout.addWidget(self.spinRollP, 2, 1, 1, 1)
        self.labelI = QtGui.QLabel(self.gridLayoutWidget)
        self.labelI.setAlignment(QtCore.Qt.AlignCenter)
        self.labelI.setObjectName(_fromUtf8("labelI"))
        self.gridLayout.addWidget(self.labelI, 0, 2, 1, 1)
        self.labelPIDControllerPitch = QtGui.QLabel(self.gridLayoutWidget)
        self.labelPIDControllerPitch.setObjectName(_fromUtf8("labelPIDControllerPitch"))
        self.gridLayout.addWidget(self.labelPIDControllerPitch, 1, 0, 1, 1)
        self.spinPitchP = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinPitchP.setObjectName(_fromUtf8("spinPitchP"))
        self.gridLayout.addWidget(self.spinPitchP, 1, 1, 1, 1)
        self.spinPitchI = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinPitchI.setObjectName(_fromUtf8("spinPitchI"))
        self.gridLayout.addWidget(self.spinPitchI, 1, 2, 1, 1)
        self.spinRollI = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinRollI.setObjectName(_fromUtf8("spinRollI"))
        self.gridLayout.addWidget(self.spinRollI, 2, 2, 1, 1)
        self.labelD = QtGui.QLabel(self.gridLayoutWidget)
        self.labelD.setAlignment(QtCore.Qt.AlignCenter)
        self.labelD.setObjectName(_fromUtf8("labelD"))
        self.gridLayout.addWidget(self.labelD, 0, 3, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(274, 120, 21, 20))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.groupBox_2 = QtGui.QGroupBox(ConsoleView)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 351, 51))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.buttonConnect = QtGui.QPushButton(self.groupBox_2)
        self.buttonConnect.setGeometry(QtCore.QRect(230, 18, 111, 30))
        self.buttonConnect.setObjectName(_fromUtf8("buttonConnect"))
        self.listConnect = QtGui.QComboBox(self.groupBox_2)
        self.listConnect.setGeometry(QtCore.QRect(10, 20, 221, 26))
        self.listConnect.setObjectName(_fromUtf8("listConnect"))
        self.groupBox_3 = QtGui.QGroupBox(ConsoleView)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 50, 331, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 306, 41))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelSensorAxisTop = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSensorAxisTop.setObjectName(_fromUtf8("labelSensorAxisTop"))
        self.gridLayout_2.addWidget(self.labelSensorAxisTop, 0, 0, 1, 1)
        self.labelSensorAxisRight = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSensorAxisRight.setObjectName(_fromUtf8("labelSensorAxisRight"))
        self.gridLayout_2.addWidget(self.labelSensorAxisRight, 0, 2, 1, 1)
        self.listAxisTop = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.listAxisTop.setObjectName(_fromUtf8("listAxisTop"))
        self.gridLayout_2.addWidget(self.listAxisTop, 0, 1, 1, 1)
        self.listAxisRight = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.listAxisRight.setObjectName(_fromUtf8("listAxisRight"))
        self.gridLayout_2.addWidget(self.listAxisRight, 0, 3, 1, 1)
        self.checkBoxSkipCalibration = QtGui.QCheckBox(self.groupBox_3)
        self.checkBoxSkipCalibration.setGeometry(QtCore.QRect(10, 90, 181, 18))
        self.checkBoxSkipCalibration.setObjectName(_fromUtf8("checkBoxSkipCalibration"))
        self.buttonCalibAccel = QtGui.QPushButton(self.groupBox_3)
        self.buttonCalibAccel.setGeometry(QtCore.QRect(0, 110, 121, 32))
        self.buttonCalibAccel.setObjectName(_fromUtf8("buttonCalibAccel"))
        self.buttonCalibGyro = QtGui.QPushButton(self.groupBox_3)
        self.buttonCalibGyro.setGeometry(QtCore.QRect(130, 110, 121, 32))
        self.buttonCalibGyro.setObjectName(_fromUtf8("buttonCalibGyro"))
        self.buttonRead = QtGui.QPushButton(ConsoleView)
        self.buttonRead.setGeometry(QtCore.QRect(470, 200, 121, 32))
        self.buttonRead.setObjectName(_fromUtf8("buttonRead"))
        self.buttonWrite = QtGui.QPushButton(ConsoleView)
        self.buttonWrite.setGeometry(QtCore.QRect(580, 200, 121, 32))
        self.buttonWrite.setObjectName(_fromUtf8("buttonWrite"))
        self.labelStatus = QtGui.QLabel(ConsoleView)
        self.labelStatus.setGeometry(QtCore.QRect(10, 560, 601, 16))
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.tabWidget = QtGui.QTabWidget(ConsoleView)
        self.tabWidget.setGeometry(QtCore.QRect(10, 220, 871, 361))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 301, 151))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelAccelZ = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelAccelZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAccelZ.setObjectName(_fromUtf8("labelAccelZ"))
        self.gridLayout_3.addWidget(self.labelAccelZ, 1, 3, 1, 1)
        self.labelAccelX = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelAccelX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAccelX.setObjectName(_fromUtf8("labelAccelX"))
        self.gridLayout_3.addWidget(self.labelAccelX, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.labelGravityZ = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelGravityZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelGravityZ.setObjectName(_fromUtf8("labelGravityZ"))
        self.gridLayout_3.addWidget(self.labelGravityZ, 2, 3, 1, 1)
        self.labelMagY = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelMagY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMagY.setObjectName(_fromUtf8("labelMagY"))
        self.gridLayout_3.addWidget(self.labelMagY, 3, 2, 1, 1)
        self.labelMagX = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelMagX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMagX.setObjectName(_fromUtf8("labelMagX"))
        self.gridLayout_3.addWidget(self.labelMagX, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 3, 1, 1)
        self.labelGravityX = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelGravityX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelGravityX.setObjectName(_fromUtf8("labelGravityX"))
        self.gridLayout_3.addWidget(self.labelGravityX, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.labelGravityY = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelGravityY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelGravityY.setObjectName(_fromUtf8("labelGravityY"))
        self.gridLayout_3.addWidget(self.labelGravityY, 2, 2, 1, 1)
        self.labelAccelY = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelAccelY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAccelY.setObjectName(_fromUtf8("labelAccelY"))
        self.gridLayout_3.addWidget(self.labelAccelY, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.labelMagZ = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelMagZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMagZ.setObjectName(_fromUtf8("labelMagZ"))
        self.gridLayout_3.addWidget(self.labelMagZ, 3, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 4, 0, 1, 1)
        self.labelQuatX = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelQuatX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelQuatX.setObjectName(_fromUtf8("labelQuatX"))
        self.gridLayout_3.addWidget(self.labelQuatX, 4, 1, 1, 1)
        self.labelQuatY = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelQuatY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelQuatY.setObjectName(_fromUtf8("labelQuatY"))
        self.gridLayout_3.addWidget(self.labelQuatY, 4, 2, 1, 1)
        self.labelQuatZ = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelQuatZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelQuatZ.setObjectName(_fromUtf8("labelQuatZ"))
        self.gridLayout_3.addWidget(self.labelQuatZ, 4, 3, 1, 1)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 180, 151, 101))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.labelRoll = QtGui.QLabel(self.gridLayoutWidget_4)
        self.labelRoll.setObjectName(_fromUtf8("labelRoll"))
        self.gridLayout_4.addWidget(self.labelRoll, 1, 1, 1, 1)
        self.labelPitch = QtGui.QLabel(self.gridLayoutWidget_4)
        self.labelPitch.setObjectName(_fromUtf8("labelPitch"))
        self.gridLayout_4.addWidget(self.labelPitch, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 2, 0, 1, 1)
        self.labelYaw = QtGui.QLabel(self.gridLayoutWidget_4)
        self.labelYaw.setObjectName(_fromUtf8("labelYaw"))
        self.gridLayout_4.addWidget(self.labelYaw, 2, 1, 1, 1)
        self.formLayoutWidget = QtGui.QWidget(self.tab_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(330, 50, 351, 281))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.glLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.glLayout.setMargin(0)
        self.glLayout.setObjectName(_fromUtf8("glLayout"))
        self.buttonReset = QtGui.QPushButton(self.tab_2)
        self.buttonReset.setGeometry(QtCore.QRect(600, 20, 81, 32))
        self.buttonReset.setObjectName(_fromUtf8("buttonReset"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.textStatus = QtGui.QTextEdit(self.tab)
        self.textStatus.setGeometry(QtCore.QRect(0, 10, 581, 271))
        self.textStatus.setObjectName(_fromUtf8("textStatus"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.groupBox_4 = QtGui.QGroupBox(ConsoleView)
        self.groupBox_4.setGeometry(QtCore.QRect(440, 0, 131, 61))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.buttonPlus = QtGui.QPushButton(self.groupBox_4)
        self.buttonPlus.setGeometry(QtCore.QRect(100, 30, 31, 21))
        self.buttonPlus.setObjectName(_fromUtf8("buttonPlus"))
        self.buttonMinus = QtGui.QPushButton(self.groupBox_4)
        self.buttonMinus.setGeometry(QtCore.QRect(60, 30, 31, 21))
        self.buttonMinus.setObjectName(_fromUtf8("buttonMinus"))
        self.labelFilterAlpha = QtGui.QLabel(self.groupBox_4)
        self.labelFilterAlpha.setGeometry(QtCore.QRect(0, 30, 51, 23))
        self.labelFilterAlpha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFilterAlpha.setObjectName(_fromUtf8("labelFilterAlpha"))
        self.groupBox_5 = QtGui.QGroupBox(ConsoleView)
        self.groupBox_5.setGeometry(QtCore.QRect(620, 50, 261, 141))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox_5)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 225, 91))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labelI_2 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.labelI_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelI_2.setObjectName(_fromUtf8("labelI_2"))
        self.gridLayout_5.addWidget(self.labelI_2, 0, 2, 1, 1)
        self.labelPIDControllerPitch_2 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.labelPIDControllerPitch_2.setObjectName(_fromUtf8("labelPIDControllerPitch_2"))
        self.gridLayout_5.addWidget(self.labelPIDControllerPitch_2, 1, 0, 1, 1)
        self.labelPIDControllerRoll_2 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.labelPIDControllerRoll_2.setObjectName(_fromUtf8("labelPIDControllerRoll_2"))
        self.gridLayout_5.addWidget(self.labelPIDControllerRoll_2, 2, 0, 1, 1)
        self.labelP_2 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.labelP_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelP_2.setObjectName(_fromUtf8("labelP_2"))
        self.gridLayout_5.addWidget(self.labelP_2, 0, 1, 1, 1)
        self.spin_pitch_q_angle = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.spin_pitch_q_angle.setSingleStep(0.01)
        self.spin_pitch_q_angle.setObjectName(_fromUtf8("spin_pitch_q_angle"))
        self.gridLayout_5.addWidget(self.spin_pitch_q_angle, 1, 1, 1, 1)
        self.spin_pitch_q_bias = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.spin_pitch_q_bias.setSingleStep(0.01)
        self.spin_pitch_q_bias.setObjectName(_fromUtf8("spin_pitch_q_bias"))
        self.gridLayout_5.addWidget(self.spin_pitch_q_bias, 1, 2, 1, 1)
        self.spin_roll_q_angle = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.spin_roll_q_angle.setSingleStep(0.01)
        self.spin_roll_q_angle.setObjectName(_fromUtf8("spin_roll_q_angle"))
        self.gridLayout_5.addWidget(self.spin_roll_q_angle, 2, 1, 1, 1)
        self.spin_roll_q_bias = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.spin_roll_q_bias.setSingleStep(0.01)
        self.spin_roll_q_bias.setObjectName(_fromUtf8("spin_roll_q_bias"))
        self.gridLayout_5.addWidget(self.spin_roll_q_bias, 2, 2, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_2.setGeometry(QtCore.QRect(274, 120, 21, 20))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))

        self.retranslateUi(ConsoleView)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConsoleView)

    def retranslateUi(self, ConsoleView):
        ConsoleView.setWindowTitle(_translate("ConsoleView", "Main Window", None))
        self.label.setText(_translate("ConsoleView", "Accel X", None))
        self.label_2.setText(_translate("ConsoleView", "Accel Y", None))
        self.labelX.setText(_translate("ConsoleView", "--.----", None))
        self.labelY.setText(_translate("ConsoleView", "--.----", None))
        self.groupBox.setTitle(_translate("ConsoleView", "PID Controller:", None))
        self.labelPIDControllerRoll.setText(_translate("ConsoleView", "Roll", None))
        self.labelP.setText(_translate("ConsoleView", "P", None))
        self.labelI.setText(_translate("ConsoleView", "I", None))
        self.labelPIDControllerPitch.setText(_translate("ConsoleView", "Pitch", None))
        self.labelD.setText(_translate("ConsoleView", "D", None))
        self.checkBox.setText(_translate("ConsoleView", "CheckBox", None))
        self.groupBox_2.setTitle(_translate("ConsoleView", "Connect:", None))
        self.buttonConnect.setText(_translate("ConsoleView", "Connect", None))
        self.groupBox_3.setTitle(_translate("ConsoleView", "Sensor:", None))
        self.labelSensorAxisTop.setText(_translate("ConsoleView", "Axis Top", None))
        self.labelSensorAxisRight.setText(_translate("ConsoleView", "Right", None))
        self.checkBoxSkipCalibration.setText(_translate("ConsoleView", "Skip Calibration on Startup", None))
        self.buttonCalibAccel.setText(_translate("ConsoleView", "Calib Accel", None))
        self.buttonCalibGyro.setText(_translate("ConsoleView", "Calib Gyro", None))
        self.buttonRead.setText(_translate("ConsoleView", "READ", None))
        self.buttonWrite.setText(_translate("ConsoleView", "WRITE", None))
        self.labelStatus.setText(_translate("ConsoleView", "Status:", None))
        self.labelAccelZ.setText(_translate("ConsoleView", "--.------", None))
        self.labelAccelX.setText(_translate("ConsoleView", "--.------", None))
        self.label_10.setText(_translate("ConsoleView", "Gravity:", None))
        self.labelGravityZ.setText(_translate("ConsoleView", "--.------", None))
        self.labelMagY.setText(_translate("ConsoleView", "--.------", None))
        self.labelMagX.setText(_translate("ConsoleView", "--.------", None))
        self.label_14.setText(_translate("ConsoleView", "Mag:", None))
        self.label_9.setText(_translate("ConsoleView", "Z", None))
        self.labelGravityX.setText(_translate("ConsoleView", "--.------", None))
        self.label_7.setText(_translate("ConsoleView", "X", None))
        self.labelGravityY.setText(_translate("ConsoleView", "--.------", None))
        self.labelAccelY.setText(_translate("ConsoleView", "--.------", None))
        self.label_3.setText(_translate("ConsoleView", "Accel:", None))
        self.labelMagZ.setText(_translate("ConsoleView", "--.------", None))
        self.label_8.setText(_translate("ConsoleView", "Y", None))
        self.label_18.setText(_translate("ConsoleView", "Quat:", None))
        self.labelQuatX.setText(_translate("ConsoleView", "--.------", None))
        self.labelQuatY.setText(_translate("ConsoleView", "--.------", None))
        self.labelQuatZ.setText(_translate("ConsoleView", "--.------", None))
        self.label_24.setText(_translate("ConsoleView", "Roll:", None))
        self.labelRoll.setText(_translate("ConsoleView", "--.----", None))
        self.labelPitch.setText(_translate("ConsoleView", "--.----", None))
        self.label_22.setText(_translate("ConsoleView", "Pitch:", None))
        self.label_23.setText(_translate("ConsoleView", "Yaw:", None))
        self.labelYaw.setText(_translate("ConsoleView", "--.----", None))
        self.buttonReset.setText(_translate("ConsoleView", "Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ConsoleView", "Detail", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ConsoleView", "Log", None))
        self.groupBox_4.setTitle(_translate("ConsoleView", "Complimentry Filter:", None))
        self.buttonPlus.setText(_translate("ConsoleView", "+", None))
        self.buttonMinus.setText(_translate("ConsoleView", "-", None))
        self.labelFilterAlpha.setText(_translate("ConsoleView", "0.00", None))
        self.groupBox_5.setTitle(_translate("ConsoleView", "Kalman Filter:", None))
        self.labelI_2.setText(_translate("ConsoleView", "q_bias", None))
        self.labelPIDControllerPitch_2.setText(_translate("ConsoleView", "Pitch", None))
        self.labelPIDControllerRoll_2.setText(_translate("ConsoleView", "Roll", None))
        self.labelP_2.setText(_translate("ConsoleView", "q_angle", None))
        self.checkBox_2.setText(_translate("ConsoleView", "CheckBox", None))

